# Generated by Django 5.2.8 on 2025-11-27 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxpayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=10, unique=True)),
                ('Phone', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('income', models.IntegerField()),
                ('tax_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('succes', 'موفق'), ('rejected', 'رد شده'), ('review', 'در حال بررسی')], max_length=20)),
                ('cteate_at', models.DateTimeField(auto_now_add=True)),
                ('taxpayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.taxpayer')),
            ],
        ),
    ]
