# Generated by Django 6.0 on 2025-12-22 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='cteate_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='taxpayer',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='case',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='income',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('success', 'موفق'), ('rejected', 'رد شده'), ('review', 'در حال بررسی')], max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='tax_amount',
            field=models.BigIntegerField(),
        ),
    ]
